
properties:

projects:
  # default project is current
  - name: current
    path: .

lifecycles:

- name: con.test1
  steps:
  - title: Test Maven Sub-Modules
    target: con.test
    properties:
      processSubModules: true

- name: con.test2
  steps:
  - title: Test Modified Maven Sub-Modules
    target: con.test
    properties:
      processSubModules: true
      modifiedOnly: true

- name: git.pull
  steps:
  - title: Clone
    target: con.git.clone
  - title: Pull
    target: con.git
    arguments:
    - pull

- name: rebuild
  steps:
  - title: Rebuild
    target: con.maven
    arguments:
    - clean
    - install
    properties:
      touchDirectory: ${touchDirectory:true}
      processSubModules: ${processSubModules:false}
      modifiedOnly: ${modifiedOnly:true}
    sort: order

- name: build
  steps:
  - title: Build
    target: con.maven
    arguments:
    - install
    properties:
      touchDirectory: ${touchDirectory:true}
      processSubModules: ${processSubModules:true}
      modifiedOnly: ${modifiedOnly:true}
    sort: order

- name: clean
  steps:
  - title: Clean
    target: con.maven
    arguments:
    - clean
    sort: order

- name: newVersion
  title: Configure new versions
  steps:
  - title: Calculate new versions
    target: con.calculateNewVersion
  - title: Set new version properties
    target: con.updatePomProperties
    selector:
      group: parent
  - title: Set new parent version
    target: con.updatePomParentVersion
    selector:
      version.changed: true
    properties:
      version: ${projects.parent.version}
  - title: Install parent pom
    target: con.maven
    arguments:
     - clean
     - install
    selector:
      group: parent
  - title: Set new project version
    target: con.maven
    arguments:
      - versions:set
      - -DnewVersion=${project.version}
    selector:
      version.changed: true
  - title: Save version history
    target: con.persistNewVersions


plugins:
  - target: con.calculateNewVersion
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: calculateNewVersion
    scope: step
  - target: con.nextSnapshotVersions
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: nextSnapshotVersions
    scope: step
  - target: con.cmd
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: cmd
  - target: con.git
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: git
  - target: con.git.clone
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: git.clone
  - target: con.maven
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: maven
  - target: con.persistNewVersions
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: persistNewVersions
    scope: step
  - target: con.test
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: test
  - target: con.updatePomProperties
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: updatePomProperties
  - target: con.updatePomParentVersion
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: updatePomParentVersion
  - target: con.validateStep
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: con.validate
    scope: step
  - target: con.validateProject
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: con.validate
  - target: con.includeLifecycle
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: con.includeLifecycle
    scope: step
    