
properties:

projects:
  # default project is current
  - name: current
    path: .

lifecycles:

- name: con.test1
  steps:
  - title: Test Maven Sub-Modules
    target: con.test
    properties:
      processSubModules: true

- name: con.test2
  steps:
  - title: Test Modified Maven Sub-Modules
    target: con.test
    properties:
      processSubModules: true
      modifiedOnly: true
      
- name: rebuild
  steps:
  - title: Rebuild
    target: con.maven
    arguments:
    - clean
    - install
    properties:
      touchDirectory: true
    sort: order

- name: build
  steps:
  - title: Rebuild
    target: con.maven
    arguments:
    - install
    properties:
      touchDirectory: true
    sort: order

- name: clean
  steps:
  - title: Clean
    target: con.maven
    arguments:
    - clean
    sort: order

- name: newVersion
  title: Configure new versions
  steps:
  - title: Calculate new versions
    target: con.calculateNewVersion
  - title: Set new version properties
    target: con.updatePomProperties
    selector:
      group: parent
  - title: Set new parent version
    target: con.updatePomParentVersion
    selector:
      version.changed: true
    properties:
      version: ${projects.parent.version}
  - title: Install parent pom
    target: con.maven
    arguments:
     - clean
     - install
    selector:
      group: parent
  - title: Set new project version
    target: con.maven
    arguments:
      - versions:set
      - -DnewVersion=${project.version}
    selector:
      version.changed: true
  - title: Save version history
    target: con.persistNewVersions


plugins:
  - target: con.calculateNewVersion
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: calculateNewVersion
    scope: step
  - target: con.cmd
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: cmd
  - target: con.git
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: git
  - target: con.maven
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: maven
  - target: con.persistNewVersions
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: persistNewVersions
    scope: step
  - target: con.test
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: test
  - target: con.updatePomProperties
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: updatePomProperties
  - target: con.updatePomParentVersion
    uri: vm:de.mhus.conductor/conductor-plugin/${conductor.version}
    mojo: updatePomParentVersion
